# --- !Ups

create table USERS (
  USER_ID BIGINT AUTO_INCREMENT,
  USER_EMAIL VARCHAR(512) NOT NULL,
  USER_FIRST_NAME VARCHAR(64),
  USER_LAST_NAME VARCHAR(64),
  API_KEY VARCHAR(128) NOT NULL,
  PRIMARY KEY (USER_ID)
); 

create unique index USER_EMAIL_IDX on USERS (USER_EMAIL);

create table POSTS (
  POST_ID BIGINT AUTO_INCREMENT,
  POST_TITLE VARCHAR(512) NOT NULL,
  POST_DESCRIPTION VARCHAR(512),
  POST_TEXT VARCHAR(2048),
  POST_USER_ID BIGINT,
  PRIMARY KEY (POST_ID),
  FOREIGN KEY (POST_USER_ID) REFERENCES USERS(USER_ID)
);

# --- !Downs

drop table USERS;
drop table POSTS;